### ISSUE TITLE
How is the relation (more specifically, the predicate) extracted?

### ISSUE THREAD

**Issue by fishiu** [Babelscape/crocodile#3]
Sorry I don't really understand the work flow of CROCODILE, how was the relation type of a triplet extracted from WikiData when we caught two named entities in a sentence? By recognizing the predicate word?

**Comment by LittlePea13** [comment]
Sorry for the late reply.

I suggest you take a look at the [paper](https://aclanthology.org/2021.findings-emnlp.204/) where it was first introduced.

Basically if the two entities are linked to Wikidata, and there is an existing relation there between the two, we propagate the label. However there are some extra steps explained in the paper (such as using NLI for filtering).

Best,
Pere-Lluis.
