### ISSUE TITLE
extract_lan.sh script

### ISSUE THREAD

**Issue by KIMDOKYOUNG** [Babelscape/crocodile#4]
Hi, I've tried to execute the extract_lan.sh script , but it results in same error.
I already add that line in the download.py script, but it doesn't work.
maybe need to add in another place??

**Comment by LittlePea13** [comment]
Hello there,

I am afraid that I will need more information about your error in order to be able to help you.

**Comment by LittlePea13** [comment]
I am going to assume your issue was resolved, feel free to reopen the issue otherwise.
