### ISSUE TITLE
Does it work well for Korean too?

### ISSUE THREAD

**Issue by zozni** [Babelscape/crocodile#5]
I have a question!
Do you also support Korean language?

**Comment by LittlePea13** [comment]
You can indeed use Crocodile with Korean. There are some language specific regex parts which I imagine can be improved, but should do its job extracting a RE dataset for Korean from Wikipedia and Wikidata.

**Comment by zozni** [comment]
hi. 

# triples
echo "download wikidata facts triples statements from wikidata truthy dump .."
wget https://dumps.wikimedia.org/wikidatawiki/entities/latest-truthy.nt.bz2


Should I change the file below on startup.sh to a triple file related to Wiki Dump in Korean? However, when I looked it up, there was no file like entry/latest_truthy.nt.bz2 on https://dumps.wikimedia.org/kowiki/.
Which file should I replace it with?

**Comment by LittlePea13** [comment]
Hi, that file is not language specific, so you just need to download normally. Language specific files are downloaded automatically if you pass the language code to the script. However, the Wikipedia dump may be downloaded manually unless you modify the Wikimapper download script as explained here:
https://github.com/Babelscape/crocodile/issues/2#issuecomment-1022047012
