### ISSUE TITLE
wikidata-triplets.py - 0 entity found

### ISSUE THREAD

**Issue by bastiennes** [Babelscape/crocodile#9]
Hello,

First of all, I want to thank you for sharing this script with the community.
I'm trying to regenerate Rebel dataset.
By using `python -m wikiextractor.wikiextractor.WikiExtractor data/$1/$1wiki-latest-pages-articles-multistream.xml.bz2 --links --language $1 --output text/$1 --templates data/$1/templates.txt`, I get page articles. 
The wikidata entities are described by theirs links ([--links](https://github.com/Babelscape/crocodile/blob/c30e3bafc16ac68b95605e299ba4c9990d7ee681/extract_lan.sh#L14)), but wikidata-triplets.py use the [wikidata ID](https://github.com/Babelscape/crocodile/blob/c30e3bafc16ac68b95605e299ba4c9990d7ee681/wikidata-triplets.py#L10). 

How did you turn the links into IDs?

**Comment by LittlePea13** [comment]
Hi there, sorry for the late reply, I didn't see the issue until now. See the Readme:

> For ./wikiextractor we use a submodule which is a fork of the original [wikiextractor](https://github.com/attardi/wikiextractor) that implements [wikimapper](https://pypi.org/project/wikimapper/) to extract the Wikidata entities. You can find the fork [here](https://github.com/LittlePea13/wikiextractor), and clone it to the corresponding folder.
